language: node_js
node_js:
- '0.10'
before_install:
- npm install -g npm
- npm install -g bower
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test -- karma.conf.js
after_script:
- cat ./coverage/PhantomJS*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
after_success:
- npm install -g firebase-tools
- if [[ "$TRAVIS_PULL_REQUEST" == "false"]] && [["$TRAVIS_BRANCH" == "master"]]; &&
  then firebase deploy; fi
env:
  global:
  - secure: GWVgYl7IBUUmrqkj8iK09vxHGOowKPxn0eYPM+HcQ7VFX2NGFLGbzFgF97j+1AFrPXKp2VJepxmJDXTeMTwjzhOzZyCOS2tAGnSMphoI1L1/LXNLGvnmxdC51VEJoaG1CthDulCigxJ1nqlwhCJ2EX4I00Sgaj7UtEErcBaj1jM=
  - secure: D62t5n8UjqxHna5MLDxuU0I4z8CevEbCQ/gSJvKLU0Kl0+lLjnE7N3I3jd7B6NqcK8DOSiQbaHF8mMC2Nb1huweQB243CcFXQbHwXMuAm5AzuFUbm+QDsu7LGnlisu0VEe4qXHssi5STv0Y0qe3XgWSDdmcre8u1qY9Z+8GaUPw=
  - secure: A6ytEN6+R4kY+NCa5aHgEgptKgDYbs1Eq5fSL5kD4Q6VBOjqGV3JwDLPMDKQHIiNmSQkhtoiR9iAl+5nPVUmTFVdXQPztVfPschZ+Hmjbalhes5ajbYGcd1EVMnO0pRoVlMJzvLU1WTexonVX5jljp1f9dS6Z+SgWpCvo5CUsAI=
  - secure: EwsXclJpZfwEuCo0dN7WxnYva5ZqT6MeWG3b+tRLtyMj21VH/f3jTDzhb1LQtzrVOXq3EZKJzNI7wYMLlz0EFV26pUeNeoWNiNnbfpMkr+zV/d2xZv6oetcF/M9mTgrko7c1Rmahc1NiHSip/VNRIyTBDjHQrgaQdORYfrV6Is8=
